In [1]:
import cv2

In [2]:
img = cv2.imread("C:/Urvi/urvi_pic.jpg", 1)

In [3]:
print(img)

[[[166 149 122]
  [166 149 122]
  [168 151 124]
  ...
  [101  93 103]
  [101  93 103]
  [101  93 103]]

 [[166 149 122]
  [166 149 122]
  [167 150 123]
  ...
  [100  92 102]
  [100  92 102]
  [100  92 102]]

 [[166 149 122]
  [166 149 122]
  [167 150 123]
  ...
  [100  92 102]
  [ 99  91 101]
  [ 99  91 101]]

 ...

 [[201 212 210]
  [201 212 210]
  [201 212 210]
  ...
  [204 217 219]
  [204 217 219]
  [204 217 219]]

 [[201 212 210]
  [201 212 210]
  [201 212 210]
  ...
  [204 217 219]
  [204 217 219]
  [204 217 219]]

 [[201 212 210]
  [201 212 210]
  [201 212 210]
  ...
  [204 217 219]
  [204 217 219]
  [204 217 219]]]


In [4]:
img_1 = cv2.imread("C:/Urvi/urvi_pic.jpg", 0)

In [5]:
print(img_1)

[[143 143 145 ...  97  97  97]
 [143 143 144 ...  96  96  96]
 [143 143 144 ...  96  95  95]
 ...
 [210 210 210 ... 216 216 216]
 [210 210 210 ... 216 216 216]
 [210 210 210 ... 216 216 216]]


In [6]:
print(type(img))

<class 'numpy.ndarray'>


In [7]:
print(img.shape) # 1280 Rows, 720 Colums, 3 channels

(1280, 720, 3)


In [8]:
print(img_1.shape) # 1280 Rows, 720 Colums, 1 channels

(1280, 720)


In [10]:
cv2.imshow("Urvi",img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [11]:
resized = cv2.resize(img, (600,600))

In [12]:
cv2.imshow("Urvi",resized)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [17]:
resized_1 = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))

In [19]:
cv2.imshow("Urvi",resized_1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
resized_2 = cv2.resize(img, (int(img.shape[1]*2), int(img.shape[0]*2)))

In [21]:
cv2.imshow("Urvi",resized_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# Create Face Cascade

face_cascade = cv2.CascadeClassifier("C:/Urvi/Machine Learning/Blog/Python/haarcascade_frontalface_default.xml")

img = cv2.imread("C:/Urvi/urvi_pic.jpg", 1)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

print(type(faces))
print(faces)

<class 'numpy.ndarray'>
[[379 273 260 260]
 [425 473 155 155]]


In [3]:
for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 3)
    
# resized = cv2.resize(img, (int(img.shape[1]), int(img.shape[0])))

cv2.imshow("Gray", img)

cv2.waitKey(0)
cv2.destroyAllWindows()